# render.yaml
# One-click deployment configuration for Render.com

services:
  # 1. PostgreSQL Database
  - name: yaba-bingo-db
    type: pserv
    plan: free # Or your preferred plan
    postgres:
      version: 14

  # 2. Django Backend Service
  - name: yaba-bingo-backend
    type: web
    plan: free # Or your preferred plan
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: yaba-bingo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure secret key
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_ALLOWED_HOSTS
        fromService:
          type: web
          name: yaba-bingo-frontend
          property: host
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        fromService:
          type: web
          name: yaba-bingo-frontend
          property: url

  # 3. React Frontend Service
  - name: yaba-bingo-frontend
    type: web
    plan: free # Or your preferred plan
    runtime: static
    repo: https://github.com/your-repo/yaba_bingo.git # IMPORTANT: Change to your repo URL
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://yaba-bingo-backend.onrender.com/api/* # The backend service URL
      - type: rewrite
        source: /*
        destination: /index.html