# render.yaml
# Version 3: Explicit Root Directory Configuration for Monorepo

services:
  # 1. PostgreSQL Database
  - name: yaba-bingo-db
    type: pserv
    plan: free
    postgres:
      version: 14

  # 2. Django Backend Service
  - name: yaba-bingo-backend
    type: web
    plan: free
    runtime: python
    # THIS IS THE KEY CHANGE: We tell Render to work inside the 'backend' folder
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: yaba-bingo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_ALLOWED_HOSTS
        fromService:
          type: web
          name: yaba-bingo-frontend
          property: host
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: yaba-bingo-frontend
          property: url

  # 3. React Frontend Service (No changes here, it's already correct)
  - name: yaba-bingo-frontend
    type: web
    plan: free
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: dist
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /index.html
```**The crucial addition is `rootDir: backend` for the `yaba-bingo-backend` service.**

---

### Also, Update the `build.sh` Script

Now that Render will automatically be inside the `backend` folder when it runs the build, we must **simplify the `build.sh` script** by removing the `cd backend` command (which is no longer needed).

Please **replace the entire content of your `build.sh` file** with this simplified version:

**File: `yaba_bingo/build.sh` (Simplified)**
```bash
#!/usr/bin/env bash
# build.sh - Simplified for use with rootDir

set -o errexit

pip install --upgrade pip
pip install -r requirements.txt

python manage.py collectstatic --no-input
python manage.py migrate