# render.yaml - FINAL
services:
  - name: yaba-bingo-db
    type: pserv
    plan: free
    postgres:
      version: 14
  - name: yaba-bingo-backend
    type: web
    plan: free
    runtime: python
    rootDir: backend
    buildCommand: "bash build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromService: { type: pserv, name: yaba-bingo-db, property: connectionString }
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_ALLOWED_HOSTS
        fromService: { type: web, name: yaba-bingo-frontend, property: host }
      - key: CORS_ALLOWED_ORIGINS
        fromService: { type: web, name: yaba-bingo-frontend, property: url }
  - name: yaba-bingo-frontend
    type: web
    plan: free
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: dist
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /index.html